version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: diffy
    ports:
      - 3000:3000
    volumes:
      - ./:/diffy
    environment:
      - DIFFY_WEB_HOST=0.0.0.0
      - DIFFY_GA_ANALYTICS_KEY=none
    stop_signal: SIGINT

